### ISSUE TITLE
provide a ID for the TOC

### ISSUE THREAD

**Issue by jtarchie** [abhinav/goldmark-toc#35]
Feature request: provide an HTML ID to the generated text

```html
<ul id="toc">
...
</ul>
```

**Comment by abhinav** [comment]
Hey @jtarchie, this is possible today with the `SetAttribute` method of the returned node.
e.g.,

```go
list := RenderList(...)
list.SetAttribute([]byte("id"), []byte("toc"))
```

I've added instructions for this to the README. The instructions only work if you're using RenderList directly (the manual method). Is that sufficient for your needs?

I'm open to goldmark-toc itself doing this automatically if an ID is specified on Extender, if that's what you're using.

**Comment by abhinav** [comment]
Actually, on second thought, it makes sense to support this on Extender for the automatic mode. I'm going to add this.

**Comment by abhinav** [comment]
Released in 0.5.0!

**Comment by jtarchie** [comment]
That was awesome! Thank you so much.

**Comment by acsqdotme** [comment]
how hard would it be to add the id to the h1 "Table of Contents" header too? would make styling a lot easier with both having the set ListID.
