### ISSUE TITLE
Support changing ID for "Table of Contents" header

### ISSUE THREAD

**Issue by abhinav** [abhinav/goldmark-toc#49]
how hard would it be to add the id to the h1 "Table of Contents" header too? would make styling a lot easier with both having the set ListID. 

edit: just remembered how ids work in html; how could I go about setting a #toctitle id to the header instead?

_Originally posted by @acsqdotme in https://github.com/abhinav/goldmark-toc/issues/35#issuecomment-1825101048_

**Comment by abhinav** [comment]
@acsqdotme added in v0.8.0. It'll pick up an ID automatically based on the title, but you can specify an override with the HeadingID option.

**Comment by acsqdotme** [comment]
woah this is awesome; thanks a ton.
