### ISSUE TITLE
[Feature Request]: Define title heading depth

### ISSUE THREAD

**Issue by nemo-omen** [abhinav/goldmark-toc#61]
Right now `Title` generates an `<h1>` tag. This would make the TOC break the correct semantic flow of the document unless the TOC title was the title of the document and the only `<h1>` on the page. I think I can adjust this by using a custom transformer (maybe? I've only been looking at this module since earlier this afternoon).

It might be good to provide a way to define the `Title`'s heading level output so it's easier to integrate the TOC into the document.

**Comment by abhinav** [comment]
Hello!
Yes, a custom transformer would allow this ([here's the default one](https://github.com/abhinav/goldmark-toc/blob/v0.9.0/transform.go)).

But I'm supportive of a TitleDepth option on Extender and Transformer that would control this, with the default being 1.
If you're willing to taking a stab at a PR for that, I'll be happy to help push it over the line.

(If you don't want any "table of contents" title at all, you can also use Inspect and RenderList directly, and then add it to the doc directly. See README and Transformer code for examples.)

**Comment by nemo-omen** [comment]
Sweet! I'll get started.
